-- -- lua/plugins/treesitter-blade.lua
-- return {
--   {
--     "nvim-treesitter/nvim-treesitter",
--     opts = function(_, opts)
--       vim.list_extend(opts.ensure_installed, {
--         "blade",
--         "php_only",
--       })
--
--       opts.parser_configs = opts.parser_configs or {}
--       opts.parser_configs.blade = {
--         install_info = {
--           url = "https://github.com/EmranMR/tree-sitter-blade",
--           files = { "src/parser.c" },
--           branch = "main",
--         },
--         filetype = "blade",
--       }
--     end,
--     config = function(_, opts)
--       -- The line below was causing the crash and should be removed.
--       -- vim.api.nvim_treesitter_start()
--
--       vim.filetype.add({
--         pattern = {
--           [".*%.blade%.php"] = "blade",
--         },
--       })
--     end,
--   },
-- }
